
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Velly King Jasper O. Marcellones
 */
public class Frame2_Home extends javax.swing.JFrame {

 
    public Frame2_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        logOut_b = new javax.swing.JButton();
        checkIn_b = new javax.swing.JButton();
        costumers_b = new javax.swing.JButton();
        sales_b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rooms", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 960, 500));

        logOut_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logOut_b.setText("LOG OUT");
        logOut_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_bActionPerformed(evt);
            }
        });
        jPanel1.add(logOut_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, -1, -1));

        checkIn_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checkIn_b.setText("CHECK IN");
        checkIn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn_bActionPerformed(evt);
            }
        });
        jPanel1.add(checkIn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        costumers_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        costumers_b.setText("COSTUMERS");
        costumers_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costumers_bActionPerformed(evt);
            }
        });
        jPanel1.add(costumers_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, -1));

        sales_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sales_b.setText("SALES");
        sales_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_bActionPerformed(evt);
            }
        });
        jPanel1.add(sales_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Hotel System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkIn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn_bActionPerformed
        Frame3_CheckIn checkIn = new Frame3_CheckIn();
        checkIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkIn_bActionPerformed

    private void costumers_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costumers_bActionPerformed
        Frame4_ViewCostumers costumers = new Frame4_ViewCostumers();
        costumers.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_costumers_bActionPerformed

    private void sales_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_bActionPerformed
        Frame5_Sales sales = new Frame5_Sales();
        sales.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sales_bActionPerformed

    private void logOut_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_bActionPerformed
      Frame1_LogIn logIn = new Frame1_LogIn();
      
      int i = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?",
              "Log Out",JOptionPane.OK_CANCEL_OPTION);
      
      if (i==0){
          logIn.setVisible(true);
          this.setVisible(false);
      }
      
    }//GEN-LAST:event_logOut_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkIn_b;
    private javax.swing.JButton costumers_b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logOut_b;
    private javax.swing.JButton sales_b;
    // End of variables declaration//GEN-END:variables
}
