
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Velly King Jasper O. Marcellones
 */
public class Frame6_CheckOut extends javax.swing.JFrame {
    
    String date,name,contact,roomNumber,checkIn,roomType;
    int paidChecker = 0;
    public Frame6_CheckOut(String date, String name,String contact,String roomNumber,String roomType) {
        initComponents();
        checkIn_d.setText(date);
        name_tf.setText(name);
        contact_tf.setText(contact);
        roomNumber_tf.setText(roomNumber);
        roomType_tf.setText(roomType);
    }
    public Frame6_CheckOut() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkOut_b = new javax.swing.JButton();
        back_b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomType_tf = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        roomNumber_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkIn_d = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contact_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        payment_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        days_tf = new javax.swing.JTextField();
        ok_b = new javax.swing.JButton();
        paid_b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkOut_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checkOut_b.setText("CHECK OUT");
        checkOut_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOut_bActionPerformed(evt);
            }
        });
        jPanel1.add(checkOut_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, -1));

        back_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back_b.setText("BACK");
        back_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bActionPerformed(evt);
            }
        });
        jPanel1.add(back_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CHECK OUT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("ROOM TYPE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        roomType_tf.setEditable(false);
        roomType_tf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(roomType_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 500, -1));

        name_tf.setEditable(false);
        name_tf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 500, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Date Checked In");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        roomNumber_tf.setEditable(false);
        roomNumber_tf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(roomNumber_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 500, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("₱");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        checkIn_d.setEditable(false);
        checkIn_d.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(checkIn_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 500, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("CONTACT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        contact_tf.setEditable(false);
        contact_tf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(contact_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 500, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("ROOM NUMBER");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        payment_tf.setEditable(false);
        payment_tf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(payment_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Enter Days in Hotel");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Payment");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        days_tf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(days_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 230, -1));

        ok_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ok_b.setText("OK");
        ok_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_bActionPerformed(evt);
            }
        });
        jPanel1.add(ok_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        paid_b.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paid_b.setText("PAID");
        paid_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid_bActionPerformed(evt);
            }
        });
        jPanel1.add(paid_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkOut_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOut_bActionPerformed
        if (paidChecker > 0) {
            
        } else {
            JOptionPane.showMessageDialog(null, "Please pay the exact payment","Error" ,JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_checkOut_bActionPerformed

    private void back_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bActionPerformed
        Frame4_ViewCostumers VC = new Frame4_ViewCostumers();
        VC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_bActionPerformed

    private void ok_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_bActionPerformed
       String days =days_tf.getText();
        
        if (days.equals("")) {
            JOptionPane.showMessageDialog(null,"Please add the days staying in hotel");
            
        } else {
            checkOut CO = new checkOut();
        
            String roomType = roomType_tf.getText();
            CO.setRoomType(roomType);
            CO.setPrice();
            CO.setDays(Integer.parseInt(days));
            payment_tf.setText(String.valueOf(CO.calDays())); 
        }
    }//GEN-LAST:event_ok_bActionPerformed

    private void paid_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid_bActionPerformed
       String pay = payment_tf.getText();
        if (pay.equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the days staying in hotel before paying");
            
        } else {
            payment_tf.setForeground(Color.green);
            paidChecker++;
        }
    }//GEN-LAST:event_paid_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame6_CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame6_CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame6_CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame6_CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame6_CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_b;
    private javax.swing.JTextField checkIn_d;
    private javax.swing.JButton checkOut_b;
    private javax.swing.JTextField contact_tf;
    private javax.swing.JTextField days_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name_tf;
    private javax.swing.JButton ok_b;
    private javax.swing.JButton paid_b;
    private javax.swing.JTextField payment_tf;
    private javax.swing.JTextField roomNumber_tf;
    private javax.swing.JTextField roomType_tf;
    // End of variables declaration//GEN-END:variables
}
